targets:
  $default:
    builders:
      isar_generator:
        generate_for:
          - "lib/features/projects/data/models/project_document.dart"
          - "lib/features/audio_comment/data/models/audio_comment_document.dart"
          - "lib/features/audio_track/data/models/audio_track_document.dart"
          - "lib/features/user_profile/data/models/user_profile_document.dart"
          - "lib/features/playlist/data/models/playlist_document.dart"
          - "lib/features/playlist/data/models/test_collection.dart"
          - "lib/features/audio_cache/shared/data/models/cached_audio_document.dart"
          - "lib/features/audio_cache/shared/data/models/cached_audio_document_unified.dart"
          - "lib/features/audio_cache/shared/data/models/cache_reference_document.dart"
          - "lib/features/audio_cache/shared/data/models/cache_metadata_document.dart"
          - "lib/core/sync/data/models/sync_metadata_document.dart"
          - "lib/core/sync/data/models/sync_operation_document.dart"
      injectable_generator|injectable_builder:
        generate_for:
          - "lib/**.dart"
      injectable_generator|injectable_config_builder:
        generate_for:
          - "lib/core/di/injection.dart" 
          