workflows:
  ios_develop_testflight:
    name: iOS Develop â†’ TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60
    triggering:
      events: [push]
      branch_patterns:
        - pattern: develop
    environment:
      xcode: 16.0
      flutter: stable
      groups: [app_store_connect]
      vars:
        FLAVOR: develop
        SCHEME: develop
        CONFIG: Release-develop
        BUNDLE_ID: com.trackflow.dev
    scripts:
      - name: ðŸ” Set up keychain
        script: keychain initialize
      - name: ðŸ“¦ Decode signing assets from BASE64 envs (optional)
        script: |
          set -euo pipefail
          PROFILES_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_DIR"
          # Decode distribution certificate if provided as BASE64
          if [ -n "${IOS_DIST_P12_B64:-}" ]; then
            echo "$IOS_DIST_P12_B64" | base64 --decode > "$CM_BUILD_DIR/ios_dist.p12"
            export IOS_DIST_P12="$CM_BUILD_DIR/ios_dist.p12"
            echo "Decoded IOS_DIST_P12 from IOS_DIST_P12_B64"
          fi
          # Decode provisioning profiles if provided as BASE64
          for NAME in IOS_PROFILE_DEV_B64 IOS_PROFILE_STAGING_B64 IOS_PROFILE_PROD_B64; do
            VAL="$(printenv "$NAME" || true)"
            if [ -n "${VAL:-}" ]; then
              OUT_NAME="${NAME%_B64}.mobileprovision"
              echo "$VAL" | base64 --decode > "$PROFILES_DIR/$OUT_NAME"
              echo "Decoded provisioning profile to $PROFILES_DIR/$OUT_NAME"
            fi
          done
      - name: ðŸªª Import distribution certificate (.p12) [optional]
        script: |
          if [ -n "${IOS_DIST_P12:-}" ] && [ -f "$IOS_DIST_P12" ]; then
            echo "Importing distribution certificate from $IOS_DIST_P12";
            keychain add-certificates --certificate "$IOS_DIST_P12" --password "$IOS_DIST_P12_PASSWORD";
          else
            echo "IOS_DIST_P12 not provided or file missing; skipping manual import and relying on App Store Connect fetched certs.";
          fi
      - name: ðŸ”Ž List signing identities (debug)
        script: keychain list-identities || true
      - name: ðŸ“„ Install manual provisioning profiles (if provided)
        script: |
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          echo "Scanning environment for .mobileprovision secure files..."
          while IFS='=' read -r name value; do
            if [[ -n "${value:-}" ]] && [[ -f "$value" ]] && [[ "$value" == *.mobileprovision ]]; then
              echo "Installing provisioning profile from $value"
              cp "$value" "$HOME/Library/MobileDevice/Provisioning Profiles/"
            fi
          done < <(env)
          echo "Installed profiles:"
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles" || true
      - name: ðŸªª Add certificates to keychain (non-fatal)
        script: keychain add-certificates || true
      - name: ðŸ§© Apply signing to Xcode project
        script: xcode-project use-profiles
      - name: ðŸ“‹ Check Flutter version
        script: flutter --version
      - name: ðŸ“¦ Get dependencies
        script: flutter pub get
      - name: ðŸ”§ Generate code
        script: flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: ðŸ”¥ Prepare Firebase config for flavor
        script: |
          set -euo pipefail
          case "${FLAVOR}" in
            develop|development)
              SRC="ios/config/development/GoogleService-Info-Dev.plist"
              DST="ios/Runner/GoogleService-Info-Dev.plist"
              ;;
            staging)
              SRC="ios/config/staging/GoogleService-Info-Staging.plist"
              DST="ios/Runner/GoogleService-Info-Staging.plist"
              ;;
            production|prod)
              SRC="ios/config/production/GoogleService-Info-Prod.plist"
              DST="ios/Runner/GoogleService-Info-Prod.plist"
              ;;
            *)
              echo "Unknown FLAVOR: ${FLAVOR}"; exit 1;
              ;;
          esac
          if [ -f "$SRC" ]; then
            echo "Copying $SRC -> $DST"
            cp -f "$SRC" "$DST"
          else
            echo "Firebase plist not found at $SRC"; exit 1;
          fi
      - name: ðŸŽ Install iOS dependencies
        script: cd ios && pod install --repo-update && cd ..
      - name: ðŸ”¨ Build IPA
        script: flutter build ipa --flavor $FLAVOR --release --verbose
      - name: ðŸ“¦ Collect IPA artifact
        script: |
          set -euo pipefail
          echo "Searching for generated IPA files..."
          find build -type f -name "*.ipa" -print || true
          DEST_DIR="build/ios/ipa"
          mkdir -p "$DEST_DIR"
          IPA_SRC="$(find build -type f -name "*.ipa" | head -n1 || true)"
          if [ -n "${IPA_SRC:-}" ] && [ -f "$IPA_SRC" ]; then
            DEST_IPA="$DEST_DIR/${SCHEME:-Runner}.ipa"
            echo "Copying $IPA_SRC -> $DEST_IPA"
            cp -f "$IPA_SRC" "$DEST_IPA"
          else
            echo "No IPA found after build"; exit 1;
          fi
    artifacts:
      - build/ios/ipa/*.ipa
      - build/**/*.ipa
      - build/ios/**/Logs/**/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Internal Testers

  ios_staging_testflight:
    name: iOS Staging â†’ TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60
    triggering:
      events: [push]
      branch_patterns:
        - pattern: staging
    environment:
      xcode: 16.0
      flutter: stable
      groups: [app_store_connect]
      vars:
        FLAVOR: staging
        SCHEME: staging
        CONFIG: Release-staging
        BUNDLE_ID: com.trackflow.staging
    scripts:
      - name: ðŸ” Set up keychain
        script: keychain initialize
      - name: ðŸ“¦ Decode signing assets from BASE64 envs (optional)
        script: |
          set -euo pipefail
          PROFILES_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_DIR"
          # Decode distribution certificate if provided as BASE64
          if [ -n "${IOS_DIST_P12_B64:-}" ]; then
            echo "$IOS_DIST_P12_B64" | base64 --decode > "$CM_BUILD_DIR/ios_dist.p12"
            export IOS_DIST_P12="$CM_BUILD_DIR/ios_dist.p12"
            echo "Decoded IOS_DIST_P12 from IOS_DIST_P12_B64"
          fi
          # Decode provisioning profiles if provided as BASE64
          for NAME in IOS_PROFILE_DEV_B64 IOS_PROFILE_STAGING_B64 IOS_PROFILE_PROD_B64; do
            VAL="$(printenv "$NAME" || true)"
            if [ -n "${VAL:-}" ]; then
              OUT_NAME="${NAME%_B64}.mobileprovision"
              echo "$VAL" | base64 --decode > "$PROFILES_DIR/$OUT_NAME"
              echo "Decoded provisioning profile to $PROFILES_DIR/$OUT_NAME"
            fi
          done
      - name: ðŸªª Import distribution certificate (.p12) [optional]
        script: |
          if [ -n "${IOS_DIST_P12:-}" ] && [ -f "$IOS_DIST_P12" ]; then
            echo "Importing distribution certificate from $IOS_DIST_P12";
            keychain add-certificates --certificate "$IOS_DIST_P12" --password "$IOS_DIST_P12_PASSWORD";
          else
            echo "IOS_DIST_P12 not provided or file missing; skipping manual import and relying on App Store Connect fetched certs.";
          fi
      - name: ðŸ”Ž List signing identities (debug)
        script: keychain list-identities || true
      - name: ðŸ“„ Install manual provisioning profiles (if provided)
        script: |
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          echo "Scanning environment for .mobileprovision secure files..."
          while IFS='=' read -r name value; do
            if [[ -n "${value:-}" ]] && [[ -f "$value" ]] && [[ "$value" == *.mobileprovision ]]; then
              echo "Installing provisioning profile from $value"
              cp "$value" "$HOME/Library/MobileDevice/Provisioning Profiles/"
            fi
          done < <(env)
          echo "Installed profiles:"
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles" || true
      - name: ðŸªª Add certificates to keychain (non-fatal)
        script: keychain add-certificates || true
      - name: ðŸ§© Apply signing to Xcode project
        script: xcode-project use-profiles
      - name: ðŸ“‹ Check Flutter version
        script: flutter --version
      - name: ðŸ“¦ Get dependencies
        script: flutter pub get
      - name: ðŸ”§ Generate code
        script: flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: ðŸ”¥ Prepare Firebase config for flavor
        script: |
          set -euo pipefail
          case "${FLAVOR}" in
            develop|development)
              SRC="ios/config/development/GoogleService-Info-Dev.plist"
              DST="ios/Runner/GoogleService-Info-Dev.plist"
              ;;
            staging)
              SRC="ios/config/staging/GoogleService-Info-Staging.plist"
              DST="ios/Runner/GoogleService-Info-Staging.plist"
              ;;
            production|prod)
              SRC="ios/config/production/GoogleService-Info-Prod.plist"
              DST="ios/Runner/GoogleService-Info-Prod.plist"
              ;;
            *)
              echo "Unknown FLAVOR: ${FLAVOR}"; exit 1;
              ;;
          esac
          if [ -f "$SRC" ]; then
            echo "Copying $SRC -> $DST"
            cp -f "$SRC" "$DST"
          else
            echo "Firebase plist not found at $SRC"; exit 1;
          fi
      - name: ðŸŽ Install iOS dependencies
        script: cd ios && pod install --repo-update && cd ..
      - name: ðŸ”¨ Build IPA
        script: flutter build ipa --flavor $FLAVOR --release --verbose
      - name: ðŸ“¦ Collect IPA artifact
        script: |
          set -euo pipefail
          echo "Searching for generated IPA files..."
          find build -type f -name "*.ipa" -print || true
          DEST_DIR="build/ios/ipa"
          mkdir -p "$DEST_DIR"
          IPA_SRC="$(find build -type f -name "*.ipa" | head -n1 || true)"
          if [ -n "${IPA_SRC:-}" ] && [ -f "$IPA_SRC" ]; then
            DEST_IPA="$DEST_DIR/${SCHEME:-Runner}.ipa"
            echo "Copying $IPA_SRC -> $DEST_IPA"
            cp -f "$IPA_SRC" "$DEST_IPA"
          else
            echo "No IPA found after build"; exit 1;
          fi
    artifacts:
      - build/ios/ipa/*.ipa
      - build/**/*.ipa
      - build/ios/**/Logs/**/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Testers