// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE5j29UJoo-Xh3SsKTTkcKkd9EFefIf1M',
    appId: '1:411076004525:web:e6205de952d55916d55424',
    messagingSenderId: '411076004525',
    projectId: 'track-flow-8e1c0',
    authDomain: 'track-flow-8e1c0.firebaseapp.com',
    storageBucket: 'track-flow-8e1c0.firebasestorage.app',
    measurementId: 'G-DG16JHGQZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYHXFfz70Hmbt3lF7SJAgege0dBXbg90Y',
    appId: '1:411076004525:android:bf617e695bb138f2d55424',
    messagingSenderId: '411076004525',
    projectId: 'track-flow-8e1c0',
    storageBucket: 'track-flow-8e1c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZOHTnrld_8Egbk1l0hXc5jA6PgjIU_ek',
    appId: '1:411076004525:ios:3ecff2d0ed586e9ad55424',
    messagingSenderId: '411076004525',
    projectId: 'track-flow-8e1c0',
    storageBucket: 'track-flow-8e1c0.firebasestorage.app',
    iosBundleId: 'com.example.trackflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZOHTnrld_8Egbk1l0hXc5jA6PgjIU_ek',
    appId: '1:411076004525:ios:3ecff2d0ed586e9ad55424',
    messagingSenderId: '411076004525',
    projectId: 'track-flow-8e1c0',
    storageBucket: 'track-flow-8e1c0.firebasestorage.app',
    iosBundleId: 'com.example.trackflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE5j29UJoo-Xh3SsKTTkcKkd9EFefIf1M',
    appId: '1:411076004525:web:c2945884550fa6b9d55424',
    messagingSenderId: '411076004525',
    projectId: 'track-flow-8e1c0',
    authDomain: 'track-flow-8e1c0.firebaseapp.com',
    storageBucket: 'track-flow-8e1c0.firebasestorage.app',
    measurementId: 'G-KGX9X0HZLV',
  );

}