// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-DEV-WEB-API-KEY',
    appId: 'YOUR-DEV-WEB-APP-ID',
    messagingSenderId: 'YOUR-DEV-SENDER-ID',
    projectId: 'trackflow-dev',
    authDomain: 'trackflow-dev.firebaseapp.com',
    storageBucket: 'trackflow-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR-DEV-ANDROID-API-KEY',
    appId: 'YOUR-DEV-ANDROID-APP-ID',
    messagingSenderId: 'YOUR-DEV-SENDER-ID',
    projectId: 'trackflow-dev',
    storageBucket: 'trackflow-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-DEV-IOS-API-KEY',
    appId: 'YOUR-DEV-IOS-APP-ID',
    messagingSenderId: 'YOUR-DEV-SENDER-ID',
    projectId: 'trackflow-dev',
    storageBucket: 'trackflow-dev.firebasestorage.app',
    iosBundleId: 'com.trackflow.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-DEV-IOS-API-KEY',
    appId: 'YOUR-DEV-IOS-APP-ID',
    messagingSenderId: 'YOUR-DEV-SENDER-ID',
    projectId: 'trackflow-dev',
    storageBucket: 'trackflow-dev.firebasestorage.app',
    iosBundleId: 'com.trackflow.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR-DEV-WEB-API-KEY',
    appId: 'YOUR-DEV-WINDOWS-APP-ID',
    messagingSenderId: 'YOUR-DEV-SENDER-ID',
    projectId: 'trackflow-dev',
    authDomain: 'trackflow-dev.firebaseapp.com',
    storageBucket: 'trackflow-dev.firebasestorage.app',
  );
}