// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-PRODUCTION-WEB-API-KEY',
    appId: 'YOUR-PRODUCTION-WEB-APP-ID',
    messagingSenderId: 'YOUR-PRODUCTION-SENDER-ID',
    projectId: 'trackflow-prod',
    authDomain: 'trackflow.app',
    storageBucket: 'trackflow-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF150aejFGMNbWEZ7uQVlenYX-DSHCuEQ',
    appId: '1:192570465818:android:e5ac6819bdc93bb1297ba3',
    messagingSenderId: '192570465818',
    projectId: 'trackflow-prod',
    storageBucket: 'trackflow-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-PRODUCTION-IOS-API-KEY',
    appId: 'YOUR-PRODUCTION-IOS-APP-ID',
    messagingSenderId: 'YOUR-PRODUCTION-SENDER-ID',
    projectId: 'trackflow-prod',
    storageBucket: 'trackflow-prod.firebasestorage.app',
    iosBundleId: 'com.trackflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-PRODUCTION-IOS-API-KEY',
    appId: 'YOUR-PRODUCTION-IOS-APP-ID',
    messagingSenderId: 'YOUR-PRODUCTION-SENDER-ID',
    projectId: 'trackflow-prod',
    storageBucket: 'trackflow-prod.firebasestorage.app',
    iosBundleId: 'com.trackflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR-PRODUCTION-WEB-API-KEY',
    appId: 'YOUR-PRODUCTION-WINDOWS-APP-ID',
    messagingSenderId: 'YOUR-PRODUCTION-SENDER-ID',
    projectId: 'trackflow-prod',
    authDomain: 'trackflow.app',
    storageBucket: 'trackflow-prod.firebasestorage.app',
  );
}