part of 'playlist_dto.dart';

// This file is generated by Isar. Do not edit manually.
// Add the following command to your build.yaml to generate this file:
// targets:
//   $default:
//     builders:
//       isar_generator:
//         options:
//           enabled: true

// Add the following import to your main.dart:
// import 'package:isar/isar.dart';

// Add the following to your pubspec.yaml:
// dependencies:
//   isar: ^0.4.0
// dev_dependencies:
//   isar_generator: ^0.4.0
//   build_runner: ^1.10.0

// Run the following command to generate this file:
// flutter pub run build_runner build

// ignore_for_file: non_constant_identifier_names, constant_identifier_names

// Schema information for Isar
@Collection()
class PlaylistDtoSchema {
  Id id = Isar.autoIncrement;
  late String name;
  late List<String> trackIds;
  late String playlistSource;
}
