// Mocks generated by Mockito 5.4.5 from annotations
// in trackflow/test/features/projects/presentation/blocs/projects_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:trackflow/features/projects/domain/entities/project.dart'
    as _i2;
import 'package:trackflow/features/projects/domain/repositories/project_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProject_0 extends _i1.SmartFake implements _i2.Project {
  _FakeProject_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProjectRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectRepository extends _i1.Mock implements _i3.ProjectRepository {
  MockProjectRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Project> createProject(_i2.Project? project) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProject,
          [project],
        ),
        returnValue: _i4.Future<_i2.Project>.value(_FakeProject_0(
          this,
          Invocation.method(
            #createProject,
            [project],
          ),
        )),
      ) as _i4.Future<_i2.Project>);

  @override
  _i4.Future<void> updateProject(_i2.Project? project) => (super.noSuchMethod(
        Invocation.method(
          #updateProject,
          [project],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteProject(String? projectId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProject,
          [projectId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Project?> getProject(String? projectId) => (super.noSuchMethod(
        Invocation.method(
          #getProject,
          [projectId],
        ),
        returnValue: _i4.Future<_i2.Project?>.value(),
      ) as _i4.Future<_i2.Project?>);

  @override
  _i4.Stream<List<_i2.Project>> getUserProjects(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProjects,
          [userId],
        ),
        returnValue: _i4.Stream<List<_i2.Project>>.empty(),
      ) as _i4.Stream<List<_i2.Project>>);

  @override
  _i4.Stream<List<_i2.Project>> getUserProjectsByStatus(
    String? userId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProjectsByStatus,
          [
            userId,
            status,
          ],
        ),
        returnValue: _i4.Stream<List<_i2.Project>>.empty(),
      ) as _i4.Stream<List<_i2.Project>>);
}
