name: 🍎 Build iOS Production → TestFlight

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios-production:
    name: 🍎 iOS Production (TestFlight Internal)
    runs-on: [self-hosted, macOS, X64]
    env:
      FLAVOR: production
      SCHEME: production
      CONFIG: Release-production
      BUNDLE_ID: com.trackflow

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: 🎯 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🔧 Generate code
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: 🔧 Configure Flutter
        run: |
          flutter config --no-analytics
          flutter config --no-cli-animations

      - name: 🔧 CocoaPods
        run: |
          set -e
          cd ios
          pod install --repo-update

      - name: 🔧 Import signing certificates
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.IOS_DIST_P12_B64 }}
          p12-password: ${{ secrets.IOS_DIST_P12_PASSWORD }}

      - name: 🔧 Download provisioning profiles (Prod)
        uses: apple-actions/download-provisioning-profiles@v3
        with:
          bundle-id: ${{ env.BUNDLE_ID }}
          issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          api-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          api-private-key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          profile-type: IOS_APP_STORE

      - name: 🧮 Set build number (timestamp)
        run: |
          NEW_BUILD_NUMBER=$(date +%Y%m%d%H%M)
          echo "NEW_BUILD_NUMBER=$NEW_BUILD_NUMBER" >> $GITHUB_ENV

      - name: 🔥 Copy Firebase plist (production)
        run: cp -f ios/config/production/GoogleService-Info-Prod.plist ios/Runner/GoogleService-Info-Prod.plist

      - name: 🔨 Build IPA (production)
        shell: bash
        run: |
          echo "🚀 Building iOS production ipa..."
          flutter build ipa --flavor "$FLAVOR" --release --verbose --export-options-plist=ios/ExportOptions.plist --build-number "$NEW_BUILD_NUMBER"
        env:
          FLUTTER_XCODE_ARGS: "-allowProvisioningUpdates"

      - name: 🧭 Locate IPA
        run: |
          set -e
          IPA=$(ls -1 build/ios/ipa/*.ipa | head -n1)
          echo "IPA_PATH=$IPA" >> $GITHUB_ENV
          echo "Found IPA at: $IPA"

      - name: ✅ Verify IPA
        run: |
          if [ -f "$IPA_PATH" ]; then
            echo "✅ IPA generated: $IPA_PATH"
            echo "📏 Size: $(du -h "$IPA_PATH" | cut -f1)"
          else
            echo "❌ IPA not found"; ls -la build/ios/ipa/; exit 1;
          fi

      - name: 🍎 Upload to TestFlight (Prod)
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: ${{ env.IPA_PATH }}
          issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          api-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          api-private-key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}


